#! /bin/sh

sxhkd &
compton -cb --config $HOME/.compton.conf &
$HOME/.config/polybar/launch.sh &
wmname LG3D
hsetroot -solid '#2d2d2d' &


bspc monitor DVI-I-1 -d I II III
bspc monitor DP-0 -d IV V VI VII
bspc monitor HDMI-0 -d VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config click_to_focus true

bspc rule -a Gimp desktop=^8 follow=on state=floating
