#!/usr/bin/env python3

import urllib.request

city = "94598"
api_key = "cdb303de7098b26a8648a071145eece6"
units = "Imperial"
unit_key = "F"

weather = eval(str(urllib.request.urlopen(
    "http://api.openweathermap.org/data/2.5/weather?q={}&APPID={}&units={}"
    .format(city, api_key, units)).read())[2:-1])

# info = weather["weather"][0]["description"].capitalize()
temp = int(float(weather["main"]["temp"]))

print("%i °%s" % (temp, unit_key))
